var = ['sebzeciliğe', 'güvenmek', 'caydırıcılığına', 'giymediğini', 'uçurtacaktır', 'normalleştiriciliğine',
       'durdurulabiliyorsanız', 'ödenemediğinden', 'yayınlamaları', 'çözemediği', 'haşin', 'şekillenmişse',
       'fırınımıza', 'yanlışlaşmasını', 'kaydettirmeleri', 'kabuklarından', 'sarılmayalım', 'yalvacıyım',
       'soruşturulabilmektedirler', 'hederleri', 'saçmalamaları', 'giyilemeyen', 'ötekileştirmesine', 'netçesinde',
       'girebildiğiniz', 'telefonlaştığını', 'taşlanırken', 'ulusçuğun', 'yıprattığınızın', 'karatmadır', 'takılık',
       'varoluşumuzdaki', 'yenilememe', 'triportörü', 'dönüşümcülerle', 'kanıtlayabiliriz', 'şeyimizle',
       'korunmayacağını', 'selamlayışları', 'arkasını', 'bütçelendirilmişti', 'desteklenmemem', 'çevirmeyecekti',
       'yalanmadı', 'hantallık', 'vedalaşıyorduk', 'açıklamamışlardı', 'susulmuşların', 'alabilmeye', 'ücretleri',
       'alınabildiğinden', 'haldense', 'anlatılansa', 'başörtüsüzlerin', 'basıldıkça', 'savaşalım', 'büyücüsünden',
       'tatman', 'denkleştirdikleri', 'genomumuzdaki', 'olumsuzlaştı', 'tartacağına', 'aylakça', 'entelleştiğinin',
       'kapamadığım', 'değimliydi', 'kesmediğim', 'seçkincilere', 'kurmamışlar', 'ölçülebileceğine', 'yakalanabilirsin',
       'siyahında', 'köylerimizdir', 'yönlendiğinizde', 'tipiklerinden', 'sallanabiliriz', 'aksettirdim',
       'süpürmüyordu', 'değiştiriverirsiniz', 'tartışılmamak', 'uygarlıklarının', 'satıverdiğini', 'genişleyebileceğim',
       'evsizken', 'bilmediğimizde', 'lisesindeydi', 'yapaylıklara', 'yüklenimi', 'sıfatlarınızın', 'meşgulsen',
       'küstahlıklarından', 'yeşermeleri', 'filizlendirmedi', 'buyrulmuş', 'tökezlemiştir', 'örtüşüyoruz', 'kusmasın',
       'alıkoymuyor', 'kızgınlıklardan', 'takılmışsınızdır', 'kalktıklarından', 'nüktedanı', 'alınmaktır',
       'yetişebilmekti', 'gösterinden', 'ayrılacakların', 'göreceğimden', 'konuşuyordunuz', 'imreniyoruz', 'lunaparkın',
       'tıngırtısı', 'gerilemeyeceği', 'yükselebilmelerini', 'evrimci', 'kurtarıcısıydı', 'değdirebiliriz',
       'boğazlarımızla', 'bidatini', 'makinemizle', 'kanatanlar', 'kanatlandı', 'indirilmeyeceğini', 'ramazana',
       'illerim', 'sürdürmeyi', 'çamlarından', 'elimdekiyle', 'sansürlüyor', 'bilgilendiremediğini', 'tipsizleştiriyor',
       'uydurmacılıkta', 'kitapçılar', 'kavuşamayacağına', 'yaşadığıdır', 'bunalımlarında', 'muştuluyorsa',
       'geçindirebildiğini', 'furyalarla', 'karyolasındaki', 'bahşedilmektedir', 'kalkılamaz', 'edilmemiştir',
       'hayvanlaşma', 'kokacağı', 'amelini', 'zenginleştiremeyenler', 'anekdottu', 'helvamı', 'afakını', 'lokmadaki',
       'yumruklarla', 'atanamazsanız', 'sömürgeleştirilmemiş', 'kampanyalarından', 'kahramanıymış', 'ruhiyatta',
       'militaristleşmiş', 'söyleyemediklerinde', 'birleşimde', 'bomlular', 'coplayanların', 'anlaşılabiliyorlar',
       'didişeyim', 'suretimizle', 'dışlanmamıza', 'bakılmadıkları', 'betimlemeleri', 'zemindedir', 'formasyonlarını',
       'melankolisinin', 'akacağım', 'falancacılar', 'çapkınlıkları', 'yapılanmamızla', 'kasılmayın', 'yumaya',
       'gagaladığında', 'bordrosunda', 'evlenememekten', 'arsenikten', 'eklenebiliyor', 'komşuluklarımız', 'voleli',
       'ihtiyatkarlığına', 'kapitalistleşeceği', 'başlığındaydı', 'piştinin', 'yedincinin', 'kökenimizden',
       'üşütmüştür', 'kapınızda', 'yıkmadıklarına', 'kullandırmışlardır', 'kaygılanmasın', 'gütmelerini', 'sinerjiden',
       'yemeyeceklerinin', 'kuşaklarıydık', 'bağlandığımda', 'birleşime', 'kopukluklarıyla', 'şenlendireyim',
       'gerçekleştirmesiydi', 'yalarsınız', 'odaklandırılacak', 'etkileyeceğimin', 'değiştirilebiliyor', 'solumama',
       'egoistleri', 'filmlerineydi', 'aşiretimizde', 'transferlerimizde', 'yalanlayınız', 'ölümsüzleştireceğim',
       'tsunamiydi', 'sığlıklara', 'çiziyle', 'kotarılmaktadır', 'aracındır', 'tedbirse', 'pazarı', 'besicisi',
       'yakıştırmadıkları', 'ahiretle', 'evcilleştirmemi', 'hikayeciliğimize', 'formüllerine', 'canlandırmayın',
       'bağlamacıya', 'ruhsatım', 'vahiylerini', 'koliler', 'şaşırtacaksın', 'sarkıtmaktı', 'kimliksizlikten',
       'çözebilseydi', 'göndericinin', 'öğütlediğine', 'görevlendirmesidir', 'süpürttüler', 'özcü', 'oluşturmamasına',
       'yalvaçlık', 'büyütüleceği', 'susamışa', 'dokunmadığımın', 'yararlandıramadı', 'katılabilmiş', 'aldırmaması',
       'yelkencimiz', 'tavsiyelerdir', 'canlandırıverdi', 'yarından', 'hizmetçilerse', 'cıkları', 'tahriklerden',
       'kalkışsalardı', 'kayalıkların', 'yenilmesin', 'sahiplendiklerimizden', 'özlere', 'memuriyetlik', 'donanıma',
       'çığırdığım', 'hoşumu', 'bilimsizliğidir', 'düzenleyebildikleri', 'detaylandıramam', 'puntosundan', 'hümanizmin',
       'büyütüyordum', 'çözülmüşler', 'gelişmişlere', 'doğumum', 'safranlı', 'istimlaklerini', 'sılasına',
       'bulgularınızı', 'koymayacağımızı', 'danelerden', 'dehada', 'değiştiğiydi', 'kırılmayabilir', 'nakaratlarda',
       'hasiyetlerimizi', 'koruyacaktık', 'ambülanstan', 'orgeneral', 'tabirlerinden', 'kırabileceği', 'uyuşmuyorlar',
       'koruyabilmişlerdir', 'sokacağımızı', 'senatörlerince', 'kilisedeydi', 'zumla', 'objektifimize',
       'beylerbeyiliği', 'iletişiminin', 'endişelilerse', 'yapamazlar', 'nakşetme', 'aslımıza', 'yalanlanmalarına',
       'tutkularıymış', 'kaygıdan', 'kodsuz', 'çantacıya', 'oynatılmazken', 'kanaryasının', 'bilebilmesine',
       'yazarımdır', 'bollukçunun', 'tanıştığının', 'bayılırlardı', 'beklentisininde', 'çevrimlerinde', 'çelmesini',
       'elenmişsin', 'uğraşamamak', 'gözlemelerden', 'tanıyamayan', 'silsiledeki', 'anlaşılacağı', 'vebalaşmaya',
       'cereyanlarının', 'kaydolamayacak', 'grevleriyle', 'utandırmıyor', 'kuşkulanılacak', 'bitpazarında', 'şişmanlar',
       'optimistim', 'çatışacaklar', 'yığınlardır', 'sürüklediğinden', 'şartnameyi', 'amaçlıyorsak', 'kırımlardan',
       'hatırı', 'dışlığını', 'imdadınaysa', 'anlatmazdık', 'yükseleceğim', 'mağduriyetiniz', 'podyumlarda',
       'erguvansa', 'kabullenmediğinde', 'göndermeyeceklere', 'giyebilse', 'tuzlası', 'yargılayamadı', 'karıştılar',
       'heyecanlanmadığına', 'ihtirasını', 'megalomanların', 'kurdurabilirler', 'yerleşsek', 'demokratikleştirilmedi',
       'çizmeyeceğiz', 'bölünürüm', 'mahallelilere', 'oralısın', 'kehanetçilik', 'gerginleşmesinde', 'brövelerimi',
       'tutmamalılar', 'gerdeği', 'yakalardaki', 'yakışmayacaksa', 'şımarıkla', 'paraşütçüler', 'pudingler',
       'taşeronlaştırmayla', 'temayüllerine', 'globülin', 'imzalanmadığında', 'onayların', 'sonsuzlaşması',
       'okuyamamakla', 'tanıdıklarınızın', 'şirketiydi', 'darılmak', 'kovabilmek', 'araklamanız', 'nemlendirilme',
       'minberlerden', 'eylülümüzü', 'yetişmesi', 'tanıştırmışlar', 'yılması', 'siluetlerin', 'meraklılarının',
       'almayacaklarının', 'yiğit', 'kalamamasına', 'iyeliğine', 'kırdırırım', 'takılmadıkları', 'sondajındaki',
       'savunuşumu', 'sevmenden', 'kökünden', 'kirlidir', 'ellenmesin', 'gözlüyorum', 'şartlamıştım', 'anlatmandı',
       'bekleyişimizse', 'döver', 'çevrenini', 'dolaşılmasının', 'donanımlıysalar', 'arzulamasınlar', 'aldırılmak',
       'çekmedim', 'numaralardan', 'rutinleşmeye', 'damlasında', 'demografisi', 'azgınlıklarını', 'unutturulmamalı',
       'takvimlere', 'ürkmelerinin', 'itişmelere', 'edinilememiştir', 'tantanasının', 'çeçeli', 'duhuliyeye',
       'müziklerinizin', 'giyindirilmesinin', 'uygulamanızın', 'mercimekse', 'tüttürüyorsunuz', 'arkadaşlarınını',
       'saydırdılar', 'adınaymış', 'şehzademin', 'laktoza', 'vurguladığım', 'vazolarında', 'tekliflerinin',
       'öğretenliği', 'uçağımızdaki', 'örterdik', 'vazgeçmeyişimizdir', 'etkilenebilmiş', 'yarışmacılarda', 'barınmam',
       'inliyorsa', 'yükleyeceğiz', 'tornacıyla', 'beyannamelerde', 'işlevimiz', 'beytülmal', 'çağrıcının', 'mücellit',
       'giysisine', 'üretemese', 'bahtiyarlıktan', 'ağırlaştırılır', 'dengeledik', 'giderebiliyor', 'korkutmama',
       'kıtalarından', 'barınıyor', 'kazanacağın', 'ulaşamayıp', 'işleyeceğine', 'şerefsizlikten', 'yayılmazdı',
       'mikrolardaki', 'devredilmesini', 'şişirelim', 'besleyebiliyor', 'meylettiğinizi', 'otogardır',
       'babalardansanız', 'yıkanlarındır', 'üstelenecekleri', 'ağdalaşmayan', 'yerdesindir', 'düşündürüldüğünü',
       'olmuşcasına', 'istenilmeme', 'işkencecisiydi', 'çakıştırmalardan', 'konfederasyona', 'uçuşumuz',
       'futbolcumuzun', 'gerdanların', 'defansa', 'işmarlar', 'zariye', 'yazımlara', 'mitingcileri', 'kasetçalarında',
       'yönlendirilmemesindendir', 'yüzlerini', 'sıvılaşmaya', 'yaklaştırmaktı', 'atomsal', 'sektirmekteki',
       'giydirmenin', 'yedirdilerse', 'misafirperverlikte', 'öğretmiyoruz', 'kakasın', 'engebelerini', 'amaçladığında',
       'hançerlenme', 'ilimizdi', 'yüklenmiştir', 'oyunculara', 'hangarlarının', 'müdürünüzden', 'evlenemeyip',
       'hasılatlara', 'desteklemektesiniz', 'vagonlarıysa', 'sarmıştın', 'poyrazdı', 'özlememiş', 'yapmayabilir',
       'yatmıyorum', 'sağlamaması', 'yıkadığımda', 'konuşturuluruz', 'moralindeki', 'kurtarılacaklarıyla',
       'selamlaşmadığı', 'vefatını', 'atışmalarında', 'başsavcılılığı', 'nitekim', 'götürmüyorsanız', 'açtırılmayacak',
       'istikrarsızdan', 'duygulu', 'üstlendiğinden', 'asılmışlığım', 'dijitalin', 'devrimciliğimin', 'tırmanabilmek',
       'aşılanamadı', 'harbisinden', 'dönüşecekti', 'yoracaklar', 'makalelerimin', 'varsıllaştım', 'şeriatıyla',
       'ayrışımcılık', 'bankerdi', 'köleleştirilmek', 'kültürleri', 'övmeseler', 'dövebileceğini', 'soyunmamıştır',
       'bencilsin', 'çocuğuydular', 'uğratılmasıdır', 'evlenmeyeyim', 'sükse', 'gelenekselleştirmesidir', 'alacacağız',
       'apaydınların', 'erdemlerin', 'beyazlanıyor', 'gençlerini', 'kabartasın', 'asmamı', 'uygulayabilirdi',
       'bileştirince', 'oturmanızdan', 'tisinde', 'kontenjansız', 'sitelerinden', 'atacığından', 'dokundurmadım',
       'eylemlerimizde', 'düşlemiştiniz', 'ortopedinin', 'taçlandırayım', 'güçsüzleştirince', 'köşelemecilerden',
       'konuşamazlar', 'gelenekselliğin', 'bombalattık', 'tavlayabileceğini', 'tophanedeki', 'delirttiğim',
       'düzelmemeleri', 'çoğunlukçuları', 'yanılmalarımı', 'sorunlarıysa', 'yararlanmıştık', 'çoklar', 'karmalarını',
       'milliliğin', 'sazımızla', 'temizlense', 'priminden', 'izleyebilmişler', 'zencisiyim', 'cesaret', 'nülerin',
       'haklarıma', 'çağrılmazlardı', 'kazançlıysa', 'kahramanlarımla', 'hatmetmiştim', 'spermlerdir', 'samimini',
       'tahayyülleriyle', 'antrenörlüğüne', 'hapsetseydin', 'resmigeçitle', 'tamızda', 'yüklenemeyen', 'onarıma',
       'ilmiği', 'kaküllerle', 'başkanlığınındaki', 'yapımızda', 'çekememeye', 'ulamış', 'oynanışını', 'hınçlısınız',
       'denetletmenizi', 'kenarsız', 'yaptırabilmekte', 'formalitesine', 'sömürgede', 'faresiyi', 'falezlerinde',
       'sürtüşünü', 'sansürlenmesiydi', 'hazmedilemediğinin', 'sormaktadır', 'kaldırılışından', 'barışıyorsa',
       'aydınlanmaları', 'lavuarında', 'övünebilecekler', 'fikirsizleşti', 'fazlalığız', 'ilgilenemedim', 'toplaşsa',
       'çarpıtılamazdı', 'tutuklanmak', 'rutinim', 'yakışanı', 'özneyiz', 'eksikliğimizden', 'yakınmadayım',
       'kepeklerle', 'posun', 'unutulurlar', 'başvuragelmiştir', 'sağlayamadığımı', 'dakikalı', 'yenerdir',
       'görselliğe', 'öbürkünü', 'öldüğündeyse', 'bunaltmadan', 'enteresan', 'yıllıklarını', 'şaşırtmamakla',
       'hevesimdir', 'uluslararasılaştırmaktır', 'kızışmışken', 'yontabildiğini', 'cidarlarının', 'kavuşacaklardır',
       'devralmamalı', 'devredildiğine', 'ardılar', 'zorbalıklarından', 'öğreticisi', 'devletçilere', 'alınlarına',
       'ödeyemediler', 'öngörüyorsan', 'yaklaştırmayıp', 'transistörden', 'ıstakozcusu', 'beklenilmeli', 'dolayacağı',
       'zaaflarımız', 'edebildiği', 'tenezzülsüzdü', 'dinamitlemeye', 'döküntülerdir', 'gölgelemeyeceğine',
       'uçaklaştırılabildi', 'kapanılabileceğini', 'övünürcesine', 'menfaatimizin', 'vesvesesidir', 'uğurlamıyorlar',
       'hükmüyle', 'sucuğumuzun', 'bozukluğun', 'ikizden', 'kanıtlayamamaktan', 'adamasından', 'makyajlıydım',
       'bilinemezcidir', 'hususiyetlerle', 'uzatacağını', 'uzlette', 'bakıcımdı', 'dökünüp', 'mükellefçe', 'bravodaki',
       'yumruklaşmanın', 'uzatıcısı', 'dosyalanmaya', 'görüledursun', 'ödeyiverin', 'akamadığı', 'desteklendiklerine',
       'maktulümüz', 'aydınlatılabilmesine', 'vurmamışsa', 'savunmazdı', 'kapitülasyonundan', 'arkadaşlıyla',
       'hareketlenmede', 'rastlamayacak', 'çağrışımlarında', 'patronunum', 'fındıklıktaki', 'kalkacağımıza', 'ünsüyle',
       'kazıklamışlardır', 'meteorolojiyi', 'bomboşmuş', 'ulaşırdım', 'gezebilmeleri', 'çağrışımlarımı', 'siperleri',
       'yaftayla', 'kaşınmayı', 'hibritlerin', 'bedduasına', 'incitilmedik', 'poğaçalarla', 'karşıyadır', 'muhatabıysa',
       'otomobilken', 'vesveseleri', 'özelleştirilinceye', 'göbeğinde', 'gerilebileceği', 'sergiliyorken', 'kapaklara',
       'hissetmeyeceğimi', 'germesini', 'algılayabilmektir', 'yorumlanmayacağı', 'hafifsenmeyecek', 'gülleler',
       'dostunuzla', 'artıklı', 'çılgınlıktaki', 'hemcinsimizdir', 'uzun', 'kemerinize', 'temennilerinden',
       'açıklayabiliriz', 'mahallemizin', 'elliliklerden', 'eğlenildiğini', 'buruşmak', 'zorlayamazsınız',
       'değerlendirmediyseniz', 'muhammes', 'ürünlerimizden', 'aptallarsa', 'yaptığınızda', 'sonucuydu',
       'dayanışmasındaki', 'koklaşmalar', 'erdiremediğim', 'horlamaya', 'kıyımızda', 'adetinde', 'unutulacağına',
       'iletkenlerden', 'dokunduklarında', 'klimacılar', 'bombalattıran', 'gömendi', 'milisleri', 'öngörüşlerimiz',
       'stilimdir', 'gelişimimden', 'geçmişinizdeki', 'galibiyetini', 'tepelemesine', 'ısınabilirim', 'köpeklik',
       'unutmadım', 'yazıdayım', 'koymamızdır', 'kopyalayıcısına', 'akciğeriz', 'teyzecim', 'vizyonsuzluklar',
       'umulabilir', 'eritemeyince', 'yıkmasına', 'puflamaktadır', 'imzamızdan', 'tavsiyeleriyse', 'esirgeyebilir',
       'çalındıklarını', 'kısırlaştırılacak', 'melanetle', 'çanağına', 'tankerlerin', 'elmaslarda', 'ezebilecek',
       'oturumcuları', 'gülümseyememe', 'çağlamasını', 'çiftliğimde', 'komutanlığımızdan', 'dolansa', 'tarıyoruz',
       'vinççiye', 'dolanmasıyla', 'belediyenizin', 'filarmoninin', 'takılarımın', 'yıldırım', 'kurabilmesidir',
       'parseli', 'kafatasçılıkta', 'bulamayış', 'katlanılabilinir', 'komutanlarıydı', 'sürtülse', 'bürüneceğe',
       'inancını', 'ananelerimizle', 'sakinleştiricidir', 'dolaştık', 'debdebelerine', 'ferasetlerine', 'semahlarda',
       'seyrettirmemiştir', 'inşaatının', 'iştirakliği', 'ispatladığından', 'kondurdukları', 'toktum',
       'uymayabiliyormuş', 'topolojileri', 'mahmurla', 'yapamamasıydı', 'yıktırdığı', 'çelecekler', 'angaryadır',
       'sığdırışı', 'karıncaezmezli', 'damarlanmanın', 'kıvırcıkları', 'güçlendirmezlerse', 'sabrımla',
       'yönlendiremememizin', 'endişelenmemize', 'rastlanılmayacağına', 'yatırılmamız', 'agusunun', 'tuzlarıyla',
       'hızlanmayın', 'nitelendirebilirsek', 'memnuniyetsizleri', 'korunacağım', 'telaşlarla', 'aktarımı', 'vazgeçerim',
       'döngüsellikleri', 'ürünleriyiz', 'gidişlerde', 'ömürlerimizi', 'akamadı', 'keseriz', 'ulaşabilmeliyiz',
       'ısırmamış', 'devresel', 'kestiriyorduk', 'lahanaları', 'saracağımıza', 'seyretmişse', 'rezilleşip',
       'milletvekilleriydik', 'basenimi', 'udileri', 'kesimlerince', 'yankılarını', 'ahbaplarını', 'ölçmüşler',
       'kampüslerle', 'yahnisiymiş', 'yavanlaştırdığını', 'abajurlarına', 'vurgulayanları', 'kozalarımı',
       'hazırlanılır', 'dalgalandırmaz', 'ilgisizliklerin', 'deliklerimize', 'başlayıversin', 'bahsetmezdik', 'acemim',
       'farklılaşır', 'barokçu', 'ittifakız', 'şeytanlaştırıldığı', 'pinekliyor', 'boşlamasından', 'gözlükçüm',
       'mısırınız', 'önemsemişimdir', 'görünebilirdik', 'zindanından', 'naftan', 'çekmeyeyim', 'açtıramadıkları',
       'görenlerdenim', 'kestiriveren', 'kurşunlanmıştır', 'nöbetçilerde', 'binmezdiniz', 'tugayındaki', 'çakmışsa',
       'uzaklaşınca', 'teorileştirmenin', 'savunduklarımıza', 'gazinoyken', 'inseli', 'kemençeleri', 'kırdığımızda',
       'sultanlıktan', 'kabullenmeyin', 'duramayacak', 'savunmasızlıktır', 'anımsadığı', 'çürümezden', 'yasakçısın',
       'bücürlerinden', 'yaptırılıyor', 'soluklandılar', 'tesisatçınız', 'dövenleri', 'bozduruyordu', 'yararlananları',
       'hissetmemişlere', 'bilgilenmek', 'yitirmiştim', 'kakmadığını', 'yiğitler', 'yaşatamamıştı', 'kızınızdır',
       'yazamayacaksınız', 'starında', 'kocadı', 'isabetsizliğini', 'belirginleştirmek', 'onluğa', 'yaktıysa',
       'endüstrileri', 'dönemimiz', 'kasapta', 'kazanmalarıyla', 'ekosisteminini', 'tatminleriyle', 'toparladığımı',
       'yargılanmadık', 'okuduk', 'sızdırmazlığıyla', 'duyda', 'katarlılar', 'alkışınız', 'kaçılmakla',
       'adamcağızlarla', 'direnebilmesindedir', 'tırmandırmasında', 'şampuanlarında', 'tüketildiği', 'seansıdır',
       'çözülmediğinden', 'izlenesi', 'müjdelemesiydi', 'kuşkularıyla', 'sayılmamasının']
